name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Ruby ${{ matrix.ruby }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby: ['2.7', '3.0', '3.1', '3.2', '3.3']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    
    - name: Install dependencies
      run: |
        gem install rake
        case "${{ matrix.ruby }}" in
          2.*|3.0|3.1)
            gem install minitest -v 5.26.1
            ;;
          *)
            gem install minitest
            ;;
        esac
    
    - name: Compile extension
      run: |
        cd ext/veb_tree
        ruby extconf.rb
        make clean || true
        make
        cd ../..
        
        mkdir -p lib/veb_tree
        
        # Copy with verbose output
        if [ -f ext/veb_tree/veb_tree.so ]; then
          cp -v ext/veb_tree/veb_tree.so lib/veb_tree/
        fi
        if [ -f ext/veb_tree/veb_tree.bundle ]; then
          cp -v ext/veb_tree/veb_tree.bundle lib/veb_tree/
        fi
        
        # List what we have
        echo "Contents of lib/veb_tree/:"
        ls -la lib/veb_tree/
    
    - name: Run tests
      run: ruby -Ilib:test test/veb_tree_test.rb
    
    - name: Test gem can be required
      run: ruby -Ilib -e "require 'veb_tree'; puts 'VebTree v' + VebTree::VERSION + ' loaded on Ruby ' + RUBY_VERSION"
